Repository HH99-6D2/ideal-lamp, pull requests merged in 2022-05, with the labels that each got.

#3 Create README.md
  README.md
Labels: documentation

#8 [FEAT] Room project init
  Room/.eslintrc.js
  Room/.prettierrc
  Room/README.md
  Room/nest-cli.json
  Room/package-lock.json
  Room/package.json
  Room/src/app.controller.spec.ts
  Room/src/app.controller.ts
  Room/src/app.module.ts
  Room/src/app.service.ts
  Room/src/main.ts
  Room/test/app.e2e-spec.ts
  Room/test/jest-e2e.json
  Room/tsconfig.build.json
  Room/tsconfig.json
Labels: enhancement

#30 Feature/user TEST + TEST PASS
  src/user/functions.js
  src/user/handlers.js
  src/user/schemas.js
  src/utils/errnos.js
  test/user-create.test.js
Labels: UnitTest, FEATURE, APITest

#31 [FEAT] Room update/delete/management list API added, all API's request type modified
  Room/src/common/configs/swagger.config.ts
  Room/src/join-rooms/join-rooms.controller.ts
  Room/src/join-rooms/join-rooms.service.ts
  Room/src/likes/likes.controller.ts
  Room/src/likes/likes.service.ts
  Room/src/regions/regions.controller.ts
  Room/src/regions/regions.service.ts
  Room/src/repositories/room.repository.ts
  Room/src/rooms/dto/create-room.dto.ts
  Room/src/rooms/dto/response-room.dto.ts
  Room/src/rooms/dto/update-room.dto.ts
  Room/src/rooms/rooms.controller.ts
  Room/src/rooms/rooms.service.ts
Labels: FEATURE

#33 [FIX] modied where condition of the query
  Room/src/rooms/rooms.service.ts
Labels: BUGFIX
